### ISSUE TITLE
Convert tutorials to .py files for sphinx

### ISSUE THREAD

**Issue by srcole** [neurodsp-tools/neurodsp#109]
after PR #111, we just need 2 more:
* filt
* sim

**Comment by TomDonoghue** [comment]
Note: when this is finished, presumably we want to drop the notebooks from the tutorials folder right? Otherwise we have duplicated code - and sphinx rebuilds the notebooks from the the rst files if anyone wants those versions of them anyways.

**Comment by TomDonoghue** [comment]
This was done with #131. Closing.
