### ISSUE TITLE
pypi description formatting - setup.py

### ISSUE THREAD

**Issue by srcole** [neurodsp-tools/neurodsp#110]
As seen at https://pypi.org/project/neurodsp/

The second paragraph is not formatted in bullets as intended. 

The final paragraph is supposed to be metadata for pypi but is just in the description.

See bycycle or fooof for functional setup.py files. They look the same to me, so I'm not sure what the difference is that makes the neurodsp pypi page not render correctly.

**Comment by TomDonoghue** [comment]
The 'classifiers' list is also not working for NDSP setup.py, but just ends up dumped to the end of the description (as opposed to being listed as properties in the sidebar).

I'm really not sure why this is. When we're ready for a new release, we should troubleshoot on the test-PYPI and figure out how to make this work,

**Comment by TomDonoghue** [comment]
It seems this had something to do with rst formatting and organization of the stuff in setup.py. Fixing the description & updating some fields seems to fix this. 

PYPItest example:
https://test.pypi.org/project/neurodsp/
