### ISSUE TITLE
New simulations

### ISSUE THREAD

**Issue by TomDonoghue** [neurodsp-tools/neurodsp#113]
Just throwing out a couple ideas of possible things to add to sims that I would be interested in talking about (at some point), and possibly working on implementing to be able to play with:
- simulate transients (ERP-like)
- simulate time-varying 1/f backgrounds

Note: edited above to more clearly reflect ideas.

**Comment by rdgao** [comment]
transients would be nice. I have an "ERP" simulator, which is just a crop of the ERP image on wikipedia, which you can add onto a background noise.

varying 1/f is already included, yeah? Unless you mean something else specifically.

**Comment by TomDonoghue** [comment]
Yeh - a couple simple ERP things would be nice / easy, as in just add 'prebuilt' ERPs, like you did, and/or 'create' some, perhaps similar to how Scott does shape-y things. 

By 'varying' 1/f I meant that the 1/f exponent varies across the signal (like, starts at 1.5, ends at 2). I don't think we have that? Not sure how easy it is to do though.

**Comment by voytek** [comment]
This would be nice to simulate an event-related slope change experiment to show that you can have event-related low power decrease with high power increase, and therefore event-related cross-frequency (amplitude to amplitude) coupling due to just slope change.

**Comment by TomDonoghue** [comment]
Since this is old & development ideas, I've moved it here: https://github.com/neurodsp-tools/Development/issues/1
