### ISSUE TITLE
Documentation issue in spectral.compute_spectrum

### ISSUE THREAD

**Issue by tyfarnan** [neurodsp-tools/neurodsp#135]
What is written in the docs as default for noverlap, if left as None, turns out to be wrong. 
This seems to arise because `noverlap=None` is passed along to spectrogram, and spectrogram has a different default for interpreting None. 

NDSP.compute_spectrum: say default to None -> nperseg/2
scipy.signal.spectrogram: actually defaults None -> nperseg/8

Note: filed with @TomDonoghue

**Comment by rdgao** [comment]
yep, you're right. It's 1/8 by default. I will fix.

**Comment by TomDonoghue** [comment]
Fixed in #141 . Closing.
