### ISSUE TITLE
Links broken

### ISSUE THREAD

**Issue by voytek** [neurodsp-tools/neurodsp#142]
All links in the Tutorials README.md are broken.

**Comment by TomDonoghue** [comment]
Yep, this is fixed in #137 - just not merged yet. The original links are before the sphinx refactor.

**Comment by voytek** [comment]
Okay, good. That sounds good then.

**Comment by TomDonoghue** [comment]
Added to #137

**Comment by TomDonoghue** [comment]
Fixed in #137 . Closing.
