### ISSUE TITLE
Add bursting code from ByCycle

### ISSUE THREAD

**Issue by TomDonoghue** [neurodsp-tools/neurodsp#149]
For consolidating time-series operations into NDSP, and making ByCycle have an NDSP dependency, the bursting code currently in ByCycle should be moved into NDSP, and integrated into the module.

**Comment by srcole** [comment]
What burst code are you saying should be moved? bycycle has 2:

* [`detect_burst_cycles`](https://github.com/bycycle-tools/bycycle/blob/master/bycycle/cyclepoints.py#L11) - a cycle-by-cycle approach, which I think should be kept in bycycle.
* [`twothresh_amp`](https://github.com/bycycle-tools/bycycle/blob/master/bycycle/burst.py#L372) - redundant with neurodsp, and should be removed from bycycle with a neurodsp reference added

**Comment by TomDonoghue** [comment]
Ahh, yeh, you're right. In my mind I had it as "ByCycle uses it's own burst detection, and that is a time-series operation", but I didn't look into the detail too much - if the burst approach of ByCycle explicitly operates on cycles, then yeh, it should stay in ByCycle. 

In that case, we should drop some of the extra stuff from ByCycle, and maybe just add a note in NDSP/burst that a potentially better approach, that operates on cycles, is available in ByCycle?

**Comment by TomDonoghue** [comment]
Closing this - as yeh, there isn't actually any burst code moving into NDSP.
