### ISSUE TITLE
NDSP: Merges & Additions

### ISSUE THREAD

**Issue by TomDonoghue** [neurodsp-tools/neurodsp#155]
Okay - so what things make sense to merge from other code, and/or areas worth expanding.

MERGES
- info metrics: do we want to add some simple info metrics?
    - basic info: https://github.com/voytekresearch/basicinfo
- 1/f related metrics:
    - DFA: https://github.com/rdgao/SpaceRecon/blob/master/nlds/dfa.py
- misc:
    - Smoothing: https://github.com/rdgao/SpaceRecon/blob/master/nlds/utils.py
        - Is this function useful for something like smoothing power spectra?

ADDITIONS
- Anything we want to aim to add to NDSP? More 1/f like metrics? (BOSC, IRASA, etc?)

**Comment by rdgao** [comment]
- windowing/epoching (trial-wise PSD)
- neuronal avalanche measures from LFP
- (weighted) permutation entropy

**Comment by TomDonoghue** [comment]
So, how about we add an `aperiodic` folder, for measures of aperiodic activity calculated on time series. 

To start, let's add DFA:
@rdgao : I don't want to claim code I didn't write. 
Could you make a branch or fork and open a PR in which you simply copy the dfa.py file from here (https://github.com/rdgao/SpaceRecon/blob/master/nlds/dfa.py) into a new folder called 'aperiodic' in NeuroDSP.

I'm happy to take it from there, and update / edit the implementation to match NDSP outlines. If you don't mind opening this PR when you get a chance, I can start doing some checks / sims with DFA for the aperiodic methods project.

**Comment by rdgao** [comment]
done

**Comment by rdgao** [comment]
some initial comparison stuff here: https://github.com/rdgao/field-echos/blob/master/notebooks/sim_timescalefree.ipynb

I added you to the repo but I think you can see everything anyway

**Comment by TomDonoghue** [comment]
This issue is broadly outdated. The aperiodic sub-module has started to be added. We can revisit if we want to add any info metrics, etc, which we might want to discuss in the Development issues (https://github.com/neurodsp-tools/Development). I'm going to close this issue here.
