### ISSUE TITLE
multidim decorator squishes tuple outputs together

### ISSUE THREAD

**Issue by rdgao** [neurodsp-tools/neurodsp#156]
For `compute_spectrum`, for example, if a 2D time series is passed in, multidim takes over (I assume), runs the function on each time-series individually, and stack the outputs together.

This usually wouldn't be a problem, except `compute_spectrum` (and several other functions in `spectral`) also return the frequency axis, which get squished into the same array, i.e. [f_axis0, psd0, f_axis1, psd1 ...], instead of a tuple, which is what `compute_spectrum` naturally does for 2D inputs.

**Comment by TomDonoghue** [comment]
Okay - fixed!

The `multidim` decorator has been updated, to:
- separate out different outputs (not stack together, as original issue here)
- stack for different dimension (so, deal with 2d outputs)
- allow for sub-selection, so it doesn't have to give duplicate info (example: gives single frequency vector, when requested, not a 2d matrix of repeated values). 

Related updates on when / how the the decorator gets applied are added across the module too. 

In the end, we should have proper & working 2D support now.
