### ISSUE TITLE
Spectral.Medfilt - fails if filter length doesn't end up being odd

### ISSUE THREAD

**Issue by tyfarnan** [neurodsp-tools/neurodsp#162]
Problem: 
In spectral.compute_spectrum_medfilt, we use the 'medfilt' scipy function, which requires the filter length input to be odd. However, we take in filter length in units of Hz, and then convert to samples, and this may end up being even, leading to things erroring out (without a clear message). 

Solution: 
Should add a check & increment by 1 if length of the filter is even.

**Comment by TomDonoghue** [comment]
Fixed!

Cleaned up conversion from Hz -> samples, and added a check to increment by 1 if not odd.
