### ISSUE TITLE
discrepancy between filt tutorial and code

### ISSUE THREAD

**Issue by danielemarinazzo** [neurodsp-tools/neurodsp#169]
In the tutorial you say that in order to avoid removing edges you should set

remove_edge_artifacts=False

while in the code the correct argument is _remove_edges_

thanks for everything!

**Comment by TomDonoghue** [comment]
Ah, yes, good catch! That's an artifact of the old API. 

A fix is now pushed to repo (with miscellaneous other small tutorial updates), and the doc site has been rebuilt!

Thank you for exploring the tutorials and letting us know this issue!
