### ISSUE TITLE
Unable to build docs.

### ISSUE THREAD

**Issue by Aniket-Pradhan** [neurodsp-tools/neurodsp#172]
Hello there!

Thanks a lot for providing neurodsp.

I was packaging neurodsp for Fedora (a Linux-based distribution), and while building the docs, I was wondering why [line #101](https://github.com/neurodsp-tools/neurodsp/blob/master/doc/conf.py#L101) in conf.py is commented. This line sets the theme path for the required bootstrap theme, and I don't see any downsides in using it.
The only downside of not using it is that some operating systems (like Fedora) which don't have the bootstrap_theme on the theme_path will fail to build the docs.

If you also agree with my query, I will be happy to submit a PR for the same as well.

**Comment by TomDonoghue** [comment]
Hey @Aniket-Pradhan - thanks for the note!

I don't think there is any particular reason line 101 is turned off. To be honest, I think maybe I just didn't know what it did, and just thought it wasn't used anywhere and so commented it out, thinking it was an un-needed extra from the sphinx template. 

I sanity checked that uncommenting that line doesn't change anything when I re-build the docs on my system - so yes if it is helpful to uncomment that line and that makes it work better on other systems, that is great! If you submit a PR to do that (and anything else that is needed to make sure it works) then I will merge it in!

**Comment by Aniket-Pradhan** [comment]
Great! Thanks for understanding.

I don't think there are any other changes required to make it work - better on other systems. I will be sending a PR soon. :smile:

**Comment by TomDonoghue** [comment]
Sounds good to me! I've merged the PR in. 

Since this hopefully covers this issue, I'm going to close this now - but feel free to re-open if there is anything else, etc!

Thank you for the contribution!
