### ISSUE TITLE
Make plot tests save out plots

### ISSUE THREAD

**Issue by TomDonoghue** [neurodsp-tools/neurodsp#191]
In FOOOF, some of the plots get saved out in demo-reports and so on. This, I find useful to eyeball these files when something related changes. Otherwise,  plot-tests do a sanity check run, but don't by themselves offer much indication of if the plot runs, but goes weird. 

What if we make all NDSP plot tests save out a copy of the plot to a `test_files` folder. Then, if there is a change to plots, it's easier to go and check these files? This can be modeled on how FOOOF does so (you can see now it sets this up in `conftest`). 

Since we have the `savefig` decorator, any plot call can be saved by adding this to the call line:
`plot_thing(data, save_fig=True, file_name='plot_thing', file_path=TESTS_PLOTS_PATH)`

@ryanhammonds - do you think this is worth adding / updating? I think it would be a fairly small update.

**Comment by ryanhammonds** [comment]
I think this is worth adding. It's more convenient than checking back and forth in a notebook, and like you said shouldn't be too much to implement. I'll work on this and make a PR.

**Comment by TomDonoghue** [comment]
Done in #207
