### ISSUE TITLE
Organize tests into folders (?)

### ISSUE THREAD

**Issue by TomDonoghue** [neurodsp-tools/neurodsp#192]
At some point when  updated FOOOF, I re-organized the tests into folder. I find this makes them a little easier to navigate, and to find things in the tests, etc. Maybe we should update NDSP tests to do the same. 

@ryanhammonds - do you think this would be a useful update?

**Comment by ryanhammonds** [comment]
I think either organization is okay. I'm use to the `test_<folder>_<module>.py ` structure, but a `<folder>/test_<module>.py` may be a bit easier to navigate. I think pytest searches recursively for test_*, so there shouldn't be any pytest setting that need to be changed?

**Comment by TomDonoghue** [comment]
Yeh, it makes no difference to `pytest`, and I don't think any settings need changing. 

I think the current layout is somewhat more common, but I just don't find it scales all that well as the module gets larger, in terms of finding things. It's a bit of file moving, but otherwise a pretty easy update. 

If we do this, I think it can be a 2.2 target, so not a priority for the next release, and we can come back to it for next release.

**Comment by TomDonoghue** [comment]
Done in #207
