### ISSUE TITLE
Tech-Audit #3: Simulations

### ISSUE THREAD

**Issue by TomDonoghue** [neurodsp-tools/neurodsp#195]
This issue is part of a 'technical audit' of `neurodsp`, with @elybrand. 

A key goal of neurodsp is to have simple simulations that create example data that exhibits descriptively similar propertties to neural data. 

For the audit of the simulations, I think the key questions are:
- A technical check of the current simulations. Are they, as proposed and implemented, technically appropriate and well defined and described for their stated goals?
- Use this as an opportunity to check and consider if current frameworks & approaches for simulations are well-posed for what we want. Are there things we should extend? Should we consider switching strategy / approach for simulations, and/or adding additional approaches / frameworks? Are there any additional features of real data we would like to simulate that we can add to the simulations?

**Comment by voytek** [comment]
This matches pretty well with the intro email I'd sent, and expands on it nicely, so thanks, @TomDonoghue! The only thing I'd add more explicitly with regards to simulation is to also leverage the simulations for generating ground-truth data for unit testing as well.

**Comment by elybrand** [comment]
I made my first round of looking over the simulations. So far, everything looks pretty good. Here are my thoughts so far.

### Small bugs
There are a few things I caught that we may want to add to the smoke tests. For example, many of the transients have a kwarg which specifies a proportion of time which a rise or fall occurs, but there's no checking if this proportion is strictly between (0, 1). Other kwargs that ask for a decay time don't necessarily restrict the time to be positive. Some examples include

```python
from neurodsp.sim import sim_cycle

n_seconds = 1
fs = 100
sig = sim_cycle(n_seconds, fs, cycle_type='sawtooth', width=1.2) # This seems semantically problematic.
sig = sim_cycle(n_seconds, fs, cycle_type='asine', rdsym=1.01) # This seems semantically problematic.
sig = sim_cycle(n_seconds, fs, cycle_type='exp', tau_d=-1) # Do we want a negative decay time, e.g. exponential blow-up?
```

I'm also a bit confused for the particular aperiodic sim `sim_poisson_pop`. Sure, when the number of neurons is large you expect central limit theorem to give you an approximately Gaussian distribution. But you can directly simulate a poisson distribution, so why not do that?

### Potential additions
The trouble I have with coming up with new sims is that 1) I haven't looked at enough real neuro signals to know what would be reasonable approximations and 2) Anything more complex than sinusoids or dirac spikes make it challenging to test other methods for accuracy.

I recall hearing that frequencies in neuro signals can be coupled in interesting ways. For example, there may be bursts of high frequencies at amplitude peaks of low frequency signals. I can't immediately think of a test we could use this sim for, but the closest approximation to this would be the `sim_bursty_oscillation`, but there you can't specify when the bursts occur. 

The other sims I thought of stemmed from my limited knowledge of financial time series. There, it's common to see sudden shifts in mean or variance. I don't know if these are phenomena that the neuro community sees, but they'd be pretty easy to implement. And as @voytek commented, I'd have to think about how we could use these for unit-testing.

**Comment by TomDonoghue** [comment]
I think it' a very good point that we are not doing parameter checking! Since I have an idea for the organization / API for this, I'm going to have a go at this one, and I'll tag you in to check it out when something is ready. 

The `sim_poisson_pop` Qs go to @rdgao 

In terms of additions / general updates for sims - I think this is actually easier for a discussion / chat / call. There are some Qs I could definitely ask, that I think would be easier to talk back and forth about, at this stage. Right now, we don't directly control phase, actual occurrence (of cycles / bursts), or relationships between oscillatory components, and these are all candidates for extension - but it's probably worth some discussion of whats worth investing in adding. Shifts in mean or variance might be interesting. Perhaps more so variance, and to be done within components - as changes in oscillations, for example, are definitely relevant. Overall - let's chat on these ideas sometime soon!

**Comment by TomDonoghue** [comment]
This issue is effectively outdated: the suggested updates for things like parameter checking were added, and discussions of extra simulations were superceeded by subsequent discussions and some new additions - so I'm going to close this one now.
