### ISSUE TITLE
Aperiodic Audit

### ISSUE THREAD

**Issue by elybrand** [neurodsp-tools/neurodsp#213]
I'm opening this issue to log some things I observe with IRASA, DFA, and other aperiodic methods we will compare FOOOF against. In particular, this may include 
- examples where any of the above methods have shortcomings or perform exceptionally well over the others, or
- some discussion on the theoretical connections between the three.

**Comment by elybrand** [comment]
When I was comparing the upsampling and down sampling methods `scipy.signal.resample_poly` and the cubic spline method that [Wen and Liu use](https://link.springer.com/content/pdf/10.1007/s10548-015-0448-0.pdf), I noticed that there were some examples where IRASA failed to accurately capture the aperiodic component. Below, I have plotted two IRASA fits on two examples of time series which are sums of sinusoids with an aperiodic component with power law exponent 2. The first plot shows the power spectrum when the periodic component has frequencies (10,11,12) and the second is when the frequencies include (2, 5, 7, 10).
![IRASA_12_11_12](https://user-images.githubusercontent.com/22420689/88743500-b88e7780-d0f9-11ea-918f-0a9eefc018b1.png)
![IRASA_2_5_7_10](https://user-images.githubusercontent.com/22420689/88743497-b75d4a80-d0f9-11ea-9d38-6e0e51188e82.png)
In these cases, it looks like the up-sampling and down-sampling are unable to shift these frequencies far enough away so that they are attenuated by the averaging of the power spectrum. Consequentially, we see spikes in the estimated power spectrum of the aperiodic component. This could mean IRASA has complications with neuro signals where the central frequencies have large variances.

**Comment by TomDonoghue** [comment]
This is _awesome_ @elybrand - thanks for diving into this! 

I am quite glad that you are independently checking and arriving at I think the same impressions we have of IRASA! 

Just a note on organization - simulations and tests of IRASA should / will probably live over on the AperiodicMethods (APM) project repo (https://github.com/voytekresearch/AperiodicMethods). Broadly, simulation tests & methods experiments tend to live in project repos, and then as we come to a consensus idea of things there, we can write in some notes into the NDSP module. If you have a notebook that does these sims, maybe you want to add it to the APM repo? We can chat about organizing simulations and tests for that repo.
