### ISSUE TITLE
[BUG] passing in hset to irasa

### ISSUE THREAD

**Issue by TomDonoghue** [neurodsp-tools/neurodsp#224]
Because of how the `hset` input is handled in the `compute_irasa` function, right now you can't pass in `hset` as an array. Since it gets checked against None, the comparison between array and None fails. This should be updated to allow for passing in `hset` as an array.

**Comment by ryanhammonds** [comment]
Array's can be compared with `if hset is None`, but not `if not hset`. This is fixed now.

**Comment by TomDonoghue** [comment]
Oh! This is a great / elegant fix! The difference between `is` and `if not` makes total sense, but I feel like I had not thought this through properly, and so didn't really know this. Thanks for the fix, and for this useful tip!

Fix merged in #225, so I'm closing this.
