### ISSUE TITLE
[MNT] - Make times vector optional in timeseries plots?

### ISSUE THREAD

**Issue by TomDonoghue** [neurodsp-tools/neurodsp#291]
I sometimes find it a bit annoying to not be able to use `plot_timeseries` with just passing a signal, with no time vector (if, for example, I'm playing around with sims, and don't want to have to bother creating the times vector). 

Making the plot work with just a signal (no times) would be pretty easy - just make times and sigs default to None, and then at the top of the function, check it either are none, assume the other is a signal, and if so, set to plot and label the timeseries based on samples, rather than time (since we won't know the time definition). 

This is a quick / easy update for the sake of laziness, but is a little messy - it basically creates two call signatures for the function, including passing a single vector as first positional argument, that gets interpreted as a a signal. A potentially useful aspect is not only supporting this use case, but extending the function to plotting signals by sample. 

So, thoughts: is this a worthy update, or is the mess not worth it? If it seems worth trying, I can make a quick PR. 

cc: @ryanhammonds

**Comment by ryanhammonds** [comment]
I'm in favor of this! I use `plt.plot` a ton to avoid needing to specify a time array in a hurry. Maybe something like: `plot_timeseries(None, sig)`?

**Comment by TomDonoghue** [comment]
done in #295
