### ISSUE TITLE
Add multitaper method for spectral density estimation

### ISSUE THREAD

**Issue by SM-Figueroa** [neurodsp-tools/neurodsp#316]
Hi, [MJ](https://github.com/mwprestonjr) and I have been talking about possibly implementing a multi-taper method for spectral density estimation within neurodsp. I've heard that there is some interest in this among other members of VoytekLab. For the time being, I have opened a pull request with an initial implementation of this method under neurodsp/spectral/power.py. Any notes of advice or collaborators are greatly appreciated. Let me know if there's anything else I can do.

[multi-taper method inspiration](https://www.youtube.com/watch?v=OBwnmiVT9TE)

[pull request](https://github.com/neurodsp-tools/neurodsp/pull/317)

**Comment by TomDonoghue** [comment]
Completed in #317
