### ISSUE TITLE
Option to modify the ampltitude of sim_oscillation. component

### ISSUE THREAD

**Issue by danieltomasz** [neurodsp-tools/neurodsp#338]
Is such option exist ? I didn't find it in documentation, I want to simulate a combined signal with multiple oscillations, I could do it separately but would be handy if I can modify the amplitude of the simulated oscillation in the same interface

**Comment by danieltomasz** [comment]
Ok, i see I should use `sim_peak_oscillation` instead.

**Comment by TomDonoghue** [comment]
`sim_peak_oscillation` is for simulating a peak with a variable bandwidth and amplitude relative to the aperiodic component. 

If you want to use `sim_combined` with one or more sinusoidal oscillations, then you can use the `component_variances` parameter to set each of their respective variances, which is equivalent to setting the amplitude of each. More info on this in the [tutorial](https://neurodsp-tools.github.io/neurodsp/auto_tutorials/sim/plot_SimulateCombined.html#sphx-glr-auto-tutorials-sim-plot-simulatecombined-py)
