### ISSUE TITLE
Split general filter function into specialized functions

### ISSUE THREAD

**Issue by srcole** [neurodsp-tools/neurodsp#99]
We talked about how the current filter function is a bit of a mess to deal with because of the different requirements for bandpass, highpass, lowpass, bandstop.

After discussing, @TomDonoghue and @rdgao and I generally agreed that it would be cleaner if we split them up into different sub-functions that could alternatively be called in addition to the general function

**Comment by srcole** [comment]
I started working on this.

If we split this up into sub-functions and want it to have the same input checking and functionality as the master function, we end up with A LOT of duplicate code, which I think is worse than how it is now.

The alternative is to make this into private functions that are called by the master function. However, there are many different parts of the master function that check what the filter type is (for raising errors, for designing the filter, for determining transition band). Therefore, approach either requires multiple private functions per filter type or still some duplicate code. In the former case, the general function is not much cleaner than it is now. In the latter case, there's again a large amount of duplicate code.

After looking into this, I think we should just keep the code as it is now and delete the issue.

Thoughts @TomDonoghue and @rdgao ?

**Comment by TomDonoghue** [comment]
Merged in #132 . Closing.
